server.port: 8091
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  #Databese
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/file_server_db
    username: postgres
    password: postgres
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
#    username: files_tmp
#    password: files_tmp
  ## Flyway
  flyway:
    url: jdbc:postgresql://localhost:5432/file_server_db
    user: postgres
    password: postgres
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  ## Hibernate Properties
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  ## MULTIPART (MultipartProperties)
  servlet.multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 2000MB
    max-request-size: 2150MB
## Hibernate Logging
logging.level:
  org.hibernate.SQL: DEBUG
  org.jooq: DEBUG

server:
  tomcat:
    max-http-post-size: 62914560
## File Storage Properties
storage:
  upload-dir: ./uploads
#  upload-url: http://localhost:8091/file-server/uploadFile
## hashids properties
hashids:
  salt: "dWG8TNmWjYz8WP6DSpUgeCmFbp9SP6XjdyPg4q4BnZaEavQfC5ghdag8FkF3t9sL"
  min-length: 64
  alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

